### ISSUE TITLE
Замечания по заданию 4

### ISSUE THREAD

**Issue by dniadzelka** [ToniaIvanova/EduPractice#2]
1. Есть ветка "task 5", но сделано только 4 задание
2. Используйте  === и точку с запятой (;)
3. Для чего подключали jQuery?

**Comment by ToniaIvanova** [comment]
> 1. Есть ветка "task 5", но сделано только 4 задание
> 2. Используйте  === и точку с запятой (;)
> 3. Для чего подключали jQuery?
